name: "CI/CD: Build Docker → Push to Docker Hub → Deploy to EC2"

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: godwin005/kifaru-backend

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}     # Set this to ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}       # Raw private key (not .pem), no passphrase
          script: |
            docker pull $IMAGE_NAME
            docker stop kifaru || true
            docker rm kifaru || true
            docker run -d --name kifaru -p 80:3000 $IMAGE_NAME
